### ISSUE TITLE
Malform manifest error

### ISSUE THREAD

**Issue by Drjacky** [itzAki07/scraper#4]
I used this on Express provider and it displayed the Maldorm manifest error

**Comment by Drjacky** [comment]
I used the raw link and it the error is gone. (although it doesn't find any stream!)
https://raw.githubusercontent.com/itzAki07/scraper/main/scraper.json

**Comment by akhil-mbo** [comment]
It's good to see people are using my scraper. FYI I don't support nor associated with syncler anymore. It is as it is. I'm working on something else which will give better user experience.

**Comment by itzAki07** [comment]
@Drjacky It's good to see people are using my scraper. FYI I don't support nor associated with syncler anymore. It is as it is. I'm working on something else which will give better user experience.
